module.exports.map = {
    'start' : { 0 : 'dispa', 1 : 'dispa', 2 : 'dispa', file : "start.html" },
    'dispa' : { 0 : 'strat', 1 : 'strat', 2 : 'strat', file : "captionimage.html", zed : "Continue", one : "", two : "" },
    'strat' : {	0 : 'rpoor', 1 : 'rpoor', 2 : 'rpoor', file : "captionimage.html", zed : "Continue", one : "", two : "" },
    'rpoor' : {	0 : 'event', 1 : 'event', 2 : 'event', file : "captionimage.html", zed : "Continue", one : "", two : "" },
    'event' : {	0 : 'fbook', 1 : 'fbook', 2 : 'fbook', file : "captionimage.html", zed : "Continue", one : "Join community meeting", two : "" },
    'fbook' : {	0 : 'sprot', 1 : 'sprot', 2 : 'sprot', file : "Facebook.html", zed : "These protests are dumb", one : "Protesting is the right of every citizen", two : "" },
    'sprot' : { 0 : 'nytim', 1 : 'nytim', 2 : 'nytim', file : "captionimage.html", zed : "Continue", one : "", two : "" },
    'nytim' : { 0 : 'spro2', 1 : 'spro2', 2 : 'spro2', file : "NYTimes.html", zed : "Continue", one : "", two : "" },
    'spro2' : { 0 : '3prot', 1 : '3prot', 2 : '1prot', file : "captionimage.html", zed : "Continue", one : "Join the police", two : "" },
    '3prot' : { 0 : '3pigs', 1 : '3pigs', 2 : '3pigs', file : "captionimage.html", zed : "Continue", one : "", two : "" },
    '3pigs' : { 0 : '3twit', 1 : '3twit', 2 : '3twit', file : "captionimage.html", zed : "Every citizen is garunteed a right to peaceful assembly", one : "The police are keeping the peace", two : "Continue" },
    '3twit' : { 0 : '3pig2', 1 : '3pig2', 2 : '3pig2', file : "Twitter.html", zed : "Retweet positive comments about police", one : "Retweet positive comments about protestors", two : "Continue" },
    '3pig2' : { 0 : '3blog', 1 : '3blog', 2 : '3blog', file : "captionimage.html", zed : "Continue", one : "", two : "" },
    '3blog' : { 0 : '3viol', 1 : '3viol', 2 : '3viol', file : "Blog.html", zed : "Comment positively about the protests", one : "Comment negatively about the protests", two : "Continue" },
    '3viol' : { 0 : '3riot', 1 : '3cage', 2 : '3cage', file : "captionimage.html", zed : "They should call in the national guard", one : "They should deescalate the police force", two : "Continue" },
    '3riot' : { 0 : 'outtr', 1 : 'outtr', 2 : 'outtr', file : "captionimage.html", zed : "Continue", one : "Write an angry letter about police abuse", two : "" },
    '3cage' : { 0 : 'outtr', 1 : 'outtr', 2 : 'outtr', file : "captionimage.html", zed : "Continue", one : "", two : "" },
    '1prot' : { 0 : '1pigs', 1 : '1pigs', 2 : '1pigs', file : "captionimage.html", zed : "Continue", one : "Volunteer to do food runs", two : "" },
    '1pigs' : { 0 : '1twit', 1 : '1twit', 2 : '1twit', file : "captionimage.html", zed : "Continue", one : "Stay away from the police", two : "Yell your rights at the police" },
    '1twit' : { 0 : '1pig2', 1 : '1pig2', 2 : '1pig2', file : "Twitter.html", zed : "Continue", one : "Share a story from being on the ground", two : "Explain in detail the reasons why the protest is legitimate" },
    '1pig2' : { 0 : '1blog', 1 : '1blog', 2 : '1blog', file : "captionimage.html", zed : "Ignore and walk away", one : "Intervene and defend the protestor", two : "Take footage: people need to see this" },
    '1blog' : { 0 : '1viol', 1 : '1viol', 2 : '1viol', file : "Blog.html", zed : "Post about the reasons for the protest", one : "Reply in depth to the criticism raised by others", two : "Continue" },
    '1viol' : { 0 : '1riot', 1 : '1cage', 2 : '1cage', file : "captionimage.html", zed : "Go home, this is too much", one : "Take footage - the world needs to see this", two : "Fight back - this country was founded on the right to protest and the right to self-defense" },
    '1riot' : { 0 : 'outtr', 1 : 'outtr', 2 : 'outtr', file : "captionimage.html", zed : "Go home", one : "Obtain footage", two : "Fight back" },
    '1cage' : { 0 : 'outtr', 1 : 'outtr', 2 : 'outtr', file : "captionimage.html", zed : "Contiue", one : "", two : "" },
    'outtr' : { 0 : '_exit', 1 : '_exit', 2 : '_exit', file : "outtro.html", zed : "", one : "", two : "" },
    '_exit' : { 0 : '_exit', 1 : '_exit', 2 : '_exit', file : "outtro.html", zed : "", one : "", two : "" }
}
