module.exports.map = {
    'start' : { 0 : 'dispa', 1 : 'dispa', 2 : 'dispa', file : "start.html" },
    'dispa' : { 0 : 'strat', 1 : 'strat', 2 : 'strat', file : "captionimage.html", zed : "Test comment number 1", one : "Test comment number 2", two : "Test comment number 3" },
    'strat' : {	0 : 'rpoor', 1 : 'rpoor', 2 : 'rpoor', file : "captionimage.html" },
    'rpoor' : {	0 : 'event', 1 : 'event', 2 : 'event', file : "captionimage.html" },
    'event' : {	0 : 'fbook', 1 : 'fbook', 2 : 'fbook', file : "captionimage.html" },
    'fbook' : {	0 : 'nlike', 1 : 'ylike', 2 : 'nlike', file : "Facebook.html" },
    'nlike' : { 0 : 'sprot', 1 : 'sprot', 2 : 'sprot', file : "Facebook.html" },
    'ylike' : { 0 : 'sprot', 1 : 'sprot', 2 : 'sprot', file : "Facebook.html" },
    'sprot' : { 0 : 'nytim', 1 : 'nytim', 2 : 'nytim', file : "captionimage.html" },
    'nytim' : { 0 : 'spro2', 1 : 'spro2', 2 : 'spro2', file : "NYTimes.html" },
    'spro2' : { 0 : '3prot', 1 : '3prot', 2 : '1prot', file : "captionimage.html" },
    '3prot' : { 0 : '3pigs', 1 : '3pigs', 2 : '3pigs', file : "captionimage.html" },
    '3pigs' : { 0 : '3twit', 1 : '3twit', 2 : '3twit', file : "captionimage.html" },
    '3twit' : { 0 : '3pig2', 1 : '3pig2', 2 : '3pig2', file : "Twitter.html" },
    '3pig2' : { 0 : '3blog', 1 : '3blog', 2 : '3blog', file : "captionimage.html" },
    '3blog' : { 0 : '3viol', 1 : '3viol', 2 : '3viol', file : "Blog.html" },
    '3viol' : { 0 : '3riot', 1 : '3cage', 2 : '3cage', file : "captionimage.html" },
    '3riot' : { 0 : '3died', 1 : '3died', 2 : '3died', file : "captionimage.html" },
    '3cage' : { 0 : '3died', 1 : '3died', 2 : '3died', file : "captionimage.html" },
    '1prot' : { 0 : '1pigs', 1 : '1pigs', 2 : '1pigs', file : "captionimage.html" },
    '1pigs' : { 0 : '1twit', 1 : '1twit', 2 : '1twit', file : "captionimage.html" },
    '1twit' : { 0 : '1pig2', 1 : '1pig2', 2 : '1pig2', file : "Twitter.html" },
    '1pig2' : { 0 : '1blog', 1 : '1blog', 2 : '1blog', file : "captionimage.html" },
    '1blog' : { 0 : '1viol', 1 : '1viol', 2 : '1viol', file : "Blog.html" },
    '1viol' : { 0 : '1riot', 1 : '1cage', 2 : '1cage', file : "captionimage.html" },
    '1riot' : { 0 : '1died', 1 : '1died', 2 : '1died', file : "captionimage.html" },
    '1cage' : { 0 : '1died', 1 : '1died', 2 : '1died', file : "captionimage.html" },
    '1died' : {	0 : '_exit', 1 : '_exit', 2 : '_exit', file : "Facebook.html" },
    '3died' : { 0 : '_exit', 1 : '_exit', 2 : '_exit', file : "Facebook.html" },
    '_exit' : { 0 : '_exit', 1 : '_exit', 2 : '_exit', file : "outtro.html" }
}
